#!/usr/bin/env sh

set -euo pipefail

if [ -d ./src/ ]
then
    rm -rf ./src/
fi

git clone https://git.suckless.org/dwm ./src/
pushd ./src/

for file in ../patches/*
do
    echo "$file"
    patch < "$file"
done

# Will activate focus on click, rather than on hover
sed -i '/\[EnterNotify\] = enternotify,/d' dwm.c
sed -i '/static void enternotify(XEvent \*e)\;/d' dwm.c

cp ../config.def.h .
sudo make clean install || exit 1

popd
cp ./assets/background.png /home/tim/Pictures/

sudo mkdir -p /usr/share/xsessions/
sudo cp ./assets/dwm.desktop /usr/share/xsessions
