#!/usr/bin/env sh

set -euo pipefail

if [ -d ./src/ ]
then
    rm -rf ./src/
fi

git clone https://git.suckless.org/dwm ./src/
pushd ./src/

for file in ../patches/*
do
    echo "$file"
    patch < "$file"
done

# Will activate focus on click, rather than on hover
sed -i '/\[EnterNotify\] = enternotify,/d' dwm.c
sed -i '/static void enternotify(XEvent \*e)\;/d' dwm.c

cp ../config.def.h .
make || exit 1

popd
cp ./assets/background.jpg /home/$USER/Pictures/
cp ./src/$(ls src) ../dwm-src/

if [ ! -d ../dwm-src/ ]
then
  git clone git@github.com:tim-hilt/dwm-src.git
fi

cd ../dwm-src/
git commit -am "bump"
git push -u origin main
