#!/usr/bin/sh

xrandr > /dev/null

DP1_STATUS=$(cat /sys/class/drm/card0/card0-DP-1/status )
DP2_STATUS=$(cat /sys/class/drm/card0/card0-DP-2/status )

if [ "connected" = "$DP1_STATUS" ]
then
    xrandr --output eDP-1 --right-of DP-1 --output DP-1 --auto --primary
elif [ "connected" = "$DP2_STATUS" ]
then
    xrandr --output eDP-1 --right-of DP-2 --output DP-2 --auto --primary
else
    xrandr --output DP-1 --off
    xrandr --output DP-2 --off
fi

hsetroot -cover /home/tim/git/dwm/assets/background.jpg > /dev/null
